### ISSUE TITLE
[v2.3] Image seems not synchronized in AviSynth+ Multi-Thread mode

### ISSUE THREAD

**Issue by qiangbro** [pinterf/fft3dfilter#1]
I use delogo.dll & logoNR.avsi to remove logo and then denoise.
You know, logoNR requires fft3dfilter by default. 
When i use FFT3DFilter-v2.1.1 and add Prefetch(4) in my script, everything works fine: the logo is removed, and that area is denoised.
The problem is, if I just replace v2.1.1 to v2.3, then something wrong will appear: the logo is removed successfully, but around the logo area, the image seems not synchronized after been denoised!?

You can see my screencaptures here:

v2.1.1, Single-Thread & MT mode, works good.
![ff_test - sample avs_20170512_112347 712](https://cloud.githubusercontent.com/assets/4646469/25981066/89c2ebac-3705-11e7-921a-e9321ebc285c.png)

v2.3 Single-Thread mode, works good.
![ff_test - sample avs_20170512_112859 542](https://cloud.githubusercontent.com/assets/4646469/25981202/58586dfc-3706-11e7-935c-1f238440b7d7.png)

v2.3, MT mode Prefetch(4), image not synchronized!?
![ff_test - sample avs_20170512_112348 523](https://cloud.githubusercontent.com/assets/4646469/25981071/91746178-3705-11e7-8979-619d1cec5c54.png)

[](url)

**Comment by pinterf** [comment]
Sorry for the delay. Just spent tens of hours on a similar problem.
FFD3DFilter is autoregistering itself as MT_SERIALIZED.
However when such filter with MT_SERIALIZED property is embedded in a user function, it seems that Avisynth+ is calling the filter instances as they were MT_NICE_FILTER which means that the internal buffers and variables would be used simultaneously. Using the same buffers from any thread in a reentrant way is not the way this filter was designed. I'll have to investigate this (when and why it occurs) in the Avisynth+ project.
You could try SetFilterMTMode("FFT3DFilter",MT_MULTI_INSTANCE,force=true) perhaps?

**Comment by qiangbro** [comment]
Yes. I added `SetFilterMTMode("FFT3DFilter",MT_MULTI_INSTANCE,force=true)` in my script, and it works.

**Comment by tuanden0** [comment]
Same problem with dfttest filter.
But if you use SetFilterMTMode("dfttest", 2, force=true) it's OK.

**Comment by pinterf** [comment]
Thanks, meanwhile found something in AVS+, by which I can revert to the working mode like it worked until July, last year, but have to test it.
